### ISSUE TITLE
JTTableViewController is not working in Swift 4

### ISSUE THREAD

**Issue by haroldogtf** [jonathantribouharet/JTTableViewController#5]
I added the  pod 'JTTableViewController' and performed pod install then the error appears:

> Argument of '#selector' refers to instance method 'fetchResults()' that is not exposed to Objective-C
> Add '@objc' to expose this instance method to Objective-C

**Comment by johnvuko** [comment]
Hi,
can you try to update to the version 2.1.1 (just released), I think the problem is fixed.

**Comment by haroldogtf** [comment]
With the update, I was able to build normally. Thanks!
